### ISSUE TITLE
Close button of Storytabs not visible after installing tiddlyclip

### ISSUE THREAD

**Issue by arunnbabu81** [buggyj/tiddlyclip-plugin#116]
https://be-rad-scribe.tiddlyhost.com

Check this wiki. Close button next to the story tabs are not visible after installation of tiddlyclip.

**Comment by buggyj** [comment]
I disabled tiddlyclip and do not see any changes...

**Comment by arunnbabu81** [comment]
https://be-rad-edition.tiddlyhost.com/
This is how it looks in the original.
I will upload a demo wiki just prior to adding the tiddlyclip and the additional addons you have shared.

**Comment by arunnbabu81** [comment]
https://be-rad-scribe-minustc.tiddlyhost.com/
Here is the demo prior to adding the tiddlyclip and the additional addons you have shared

**Comment by buggyj** [comment]
the tiddler that creates the story tabs is different between these tiddlywikis -

$:/themes/be-rad/AboveRiver/TabsBar/TiddlerTabs

And that is why you are seeing a difference

**Comment by arunnbabu81** [comment]
I usually keep a changelog like title of my wikis....so that I can track any bugs like these....when I checked my wiki list, I found that the close button started disappearing after one particular wiki......and that wikis title showed only tiddlyclip in the changelog....thats why I suspected tiddlyclip .....sorry for the misunderstanding....I will investigate it further.....I remember changing that particular tiddler aftee seeing a post in the forum discussion....

**Comment by arunnbabu81** [comment]
The close button got deleted from the $:/themes/be-rad/AboveRiver/TabsBar/TiddlerTabs after I edited that tiddler a few days back. That's why it was missing. Sorry for the trouble @buggyj
