### ISSUE TITLE
nodejs wiki

### ISSUE THREAD

**Issue by linonetwo** [buggyj/tiddlyclip-plugin#122]
I hope I can integrate this with TidGi desktop app, which is a launcher for nodejs wiki.

Can you add some config to allow this send message to ndoejs rest API?

**Comment by buggyj** [comment]
Tiddlyclip-plugin (a tiddlywiki plugin) works with the tiddlyclip browser addon/extension via inter-tab messages. The addon/extension does not use the rest API.

**Comment by linonetwo** [comment]
Okay, I still have no time for https://github.com/mika-cn/maoxian-web-clipper/pull/172#issuecomment-866155666

**Comment by linonetwo** [comment]
We are planning to make a clipper for nodejs/Tidgi in https://github.com/mika-cn/maoxian-web-clipper/pull/172

**Comment by linonetwo** [comment]
https://github.com/tiddly-gittly/Browser-Extension-Tiddlywiki-Collector
