### ISSUE TITLE
Clipping of local video files not working after upgrading to new tiddlyclip version

### ISSUE THREAD

**Issue by arunnbabu81** [buggyj/tiddlyclip-plugin#125]
![image](https://github.com/buggyj/tiddlyclip-plugin/assets/67494083/6e72ea3b-59d7-4c2f-9036-2cc0b2d0d8e0)

On trying to clip local video files after upgrading to new tiddlyclip version, I am getting this error message.

I could find one sublink related tiddler in my wiki

![image](https://github.com/buggyj/tiddlyclip-plugin/assets/67494083/4e9ff788-eccd-439c-804a-a849f13e5e61)

**Comment by buggyj** [comment]
it is a shadow tiddler - I guess it is overridden - try deleting it

**Comment by arunnbabu81** [comment]
Can you check in this wiki- https://tiddlyclip-test.tiddlyhost.com/. I couldn't fix it by deleting the sublink macro tiddler

**Comment by buggyj** [comment]
From the search for `sublink` I see a match in

`$:/plugins/Gk0Wk/echarts/echarts.min.js`

so maybe tiddlyclip will not work with echarts

**Comment by arunnbabu81** [comment]
I deleted all echarts related tiddlers from the demo wiki, still local video files are not getting clipped. I am getting the same error

![image](https://github.com/buggyj/tiddlyclip-plugin/assets/67494083/21f710ae-d5d0-4054-855f-3f790865a54f)

**Comment by buggyj** [comment]
delete

`$:/bj/tiddlyclip/substringplus`


give the tiddlywiki a title

**Comment by arunnbabu81** [comment]
Now its is working. Is substringplus not needed with the latest tiddlyclip version ? You gave it during this discussion - https://github.com/buggyj/tiddlyclip-plugin/discussions/98

**Comment by buggyj** [comment]
It is not needed. Some of the modifications that you were given will have been included in the new version.
