### ISSUE TITLE
undefined on clipping snaps as separate tiddlers

### ISSUE THREAD

**Issue by arunnbabu81** [buggyj/tiddlyclip-plugin#132]
https://tiddlyclip-bug.tiddlyhost.com/

When I try to clip snaps as separate tiddler using local-tiddlyclip rules, I am getting a `undefined` text in the body of the image tiddler. 

![image](https://github.com/user-attachments/assets/c477563e-4f9d-4bf3-8f69-271db482e753)

Why does it happen ?

All relevant tiddlers are seen in the home page of the demo wiki.

**Comment by buggyj** [comment]
I don't understand which rule you are using, or what you are trying to clip? - a pdf on you local machine?

**Comment by buggyj** [comment]
There are a number of things wrong - the rule tid should be like this:

![image](https://github.com/user-attachments/assets/b834bd70-5704-4e8c-b7eb-a056ae23c48d)


check that you have 'save media' browser addon installed and enabled

You are using the '@saveto()' macro which expects  (title,text,subdir), but in your rule #fieldvalue is an empty string,

and './files' should be removed

`$text=((*$text*))[img[./files/((*@saveto(#astr,@clipsnap,#fieldvalue)*))]]\n`

**Comment by arunnbabu81** [comment]
> There are a number of things wrong - the rule tid should be like this:
> 
> ![image](https://github.com/user-attachments/assets/b834bd70-5704-4e8c-b7eb-a056ae23c48d)
> 
> 
> check that you have 'save media' browser addon installed and enabled
> 
> You are using the '@saveto()' macro which expects  (title,text,subdir), but in your rule #fieldvalue is an empty string,
> 
> and './files' should be removed
> 
> `$text=((*$text*))[img[./files/((*@saveto(#astr,@clipsnap,#fieldvalue)*))]]\n`



./files/ is needed since I am storing my images in a subfolder of files. I transfer my images to this subfolder after autosaving using savemedia addon.

Why are you saying that #fieldvalue is empty. The same thing is working fine in another rule I am using

**Comment by buggyj** [comment]
If your #fieldvalue is "" then the snap will be stored in the same dir as the tiddlywiki, not in any subdir, whereas using the prefix "./file/" says that they are located in that subdir. So that is inconsistent, and appears to me as an error, however if you are moving the files with an external program that would work.
 
In your test wiki I see in the tiddler 'mogad_tweet_daniel_gewolb_mri.png'

`
[img[./files/error no saver extension found]]
undefined
`
'error no saver extension found' is because media saver is not installed or is not working, and this causes the 'undefined' to appear.

**Comment by arunnbabu81** [comment]
> In your test wiki I see in the tiddler 'mogad_tweet_daniel_gewolb_mri.png'\n\n[img[./files/error no saver extension found]] undefined\n'error no saver extension found' is because media saver is not installed or is not working, and this causes the 'undefined' to appear.

Is save media add on installed in the browser which you are testing. I have it installed.

**Comment by buggyj** [comment]
you need to change the rule tid as shown above to avoid the undefined. 

tiddlyclip is calling to the save media extension.  and 'error no saver extension found' is being returned.

The save media extension connects to all tiddlywiki whose url start with 'file:/' i.e. are located on local disk.

Either save media is not working or the tiddlywiki does not have a url starting with 'file:/' 

which browser/version are you using?

**Comment by arunnbabu81** [comment]
Sorry for the confusion. I didn't look at the screenshot you shared carefully.. Once I made the changes as shown in that screenshot, the undefined is cleared now
