### ISSUE TITLE
Unable to install TC in tiddlywiki classic

### ISSUE THREAD

**Issue by lorian** [buggyj/tiddlyclip-plugin#29]
There's a few mentions of TWc in the repository, but I can't install the plugin directly from http://tiddlyclip.tiddlyspot.com/. Is there a way I can get tiddlyclip working with classic currently?

**Comment by buggyj** [comment]
I've put a version of the plugin here 
http://tiddlyclipclassic.tiddlyspot.com/

**Comment by lorian** [comment]
Thank you so much! My only issue is whenever I snip something, I get a pop-up error in my tiddlywiki, "source: invalid val @extraTags". I thought it might be my weird firefox configuration, but I tried it in a fresh firefox ESR install and got the same popup. The tiddler is correctly created, but that popup appears every time. Any idea what's up with it?

**Comment by buggyj** [comment]
I am using this prerelease version of tiddyclip and dont see a problem:

https://github.com/buggyj/tiddlyclip/releases/download/0.1.2/tiddlyclip-0.1.2-an.fx.xpi

**Comment by lorian** [comment]
When I try to install that version, I get told it's not compatible with Firefox 52.6.0. The version I have installed is 0.0.9, from the tiddlyspot.

**Comment by buggyj** [comment]
Unfortunately I do not have the time to support the old releases of ff.
