### ISSUE TITLE
Add the url only once while clipping text from the same website or pdf

### ISSUE THREAD

**Issue by arunnbabu81** [buggyj/tiddlyclip-plugin#38]
Currently whenever I clip some text using tiddlyclip from a website or pdf, an url also gets added along with the text into that tiddler. That means if I am clipping text multiple times from the same website or pdf, for each clipped text , an url also gets added. Is there any way to avoid this and add the url only once if I am doing text clipping multiple times from the same website or pdf?

**Comment by buggyj** [comment]
you can edit the tiddler content of  "defaultSnip"

`\rules only table wikilink prettylink

|!Title|!Body|!Tags|!Fields modifiers|!field initials|!Modes|
|((*@pageTitle*))|((*@text*))\n\n|||{"$text":"((*@pageRef*))\n\n"},{"$location":"((*@pageRef*))"},{"$caption":"((*@pageTitle*))"},{"$when":"((*@dateTimeShort*))"}|append add|`

**Comment by arunnbabu81** [comment]
Thank you very much.

Now I can easily convert the clipped text into a streams list as asked in this [issue](https://github.com/buggyj/tiddlyclip-plugin/issues/35#issue-751043692) using streams shortcut (alt+enter shortcut which splits long text into individual nodes)
