### ISSUE TITLE
Help needed regarding clipping html

### ISSUE THREAD

**Issue by arunnbabu81** [buggyj/tiddlyclip-plugin#44]
<img width="1608" alt="image" src="https://user-images.githubusercontent.com/67494083/148807910-cd004998-aac2-4b5f-8302-f24b4f966de2.png">

I tried to add html rule tid as discussed in this [google group post](https://groups.google.com/g/tiddlywiki/c/YOcEY1SSPDg/m/sRDPDjFSBgAJ). However the html category is not seen in the browser context menu.

These are the tiddler I created

<img width="559" alt="image" src="https://user-images.githubusercontent.com/67494083/148808566-9567b7d3-202b-42bd-82fd-a52c63503720.png">

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/67494083/148808651-ab2e4044-0a46-4ab3-8abd-d63b5362094c.png">

This is the context menu in Firefox
<img width="956" alt="image" src="https://user-images.githubusercontent.com/67494083/148809148-f458e47a-6c4c-4d63-a645-33e628ec7091.png">

**Comment by buggyj** [comment]
that looks ok  - try re-docking or reloading the tiddlywiki into the browser

**Comment by arunnbabu81** [comment]
> that looks ok - try re-docking or reloading the tiddlywiki into the browser

I tried both many times, but the html option is not coming in the context menu

**Comment by buggyj** [comment]
I have never had it not work.... 
I would guess that it cannot find the TiddlyClipConfig tiddler, and you are seeing the default menu.
Your tiddlywiki appears to have a rather strange name - you could try  renaming  it to a simple name without spaces
are you using firefox or another browser?

**Comment by arunnbabu81** [comment]
I created a demo wiki and I am attaching that file here.

[Demo.html.zip](https://github.com/buggyj/tiddlyclip-plugin/files/7841746/Demo.html.zip)

Are you able to get the html option in the context menu using this attached wiki?

I am using Firefox. I renamed the wiki's into a simple one word name and tried, but no success.

Can this be because I am using a old version of the plug in?

**Comment by buggyj** [comment]
yes you will need the new plugin for tw versions greater than 5.2.0

On a separate note, I see you are using the pre-release version of 5.2.2 - generally it is a bad idea to use the pre-release a part from developers.

**Comment by arunnbabu81** [comment]
I could find the html option in context menu when I used 5.1.23

When to expect the updated plug in to be released so that I can use it in my main wiki

i use 5.2.1  in my main wiki. The pre release version was used just to create the demo wiki

**Comment by arunnbabu81** [comment]
Could you please set up **Discussions** for the Tiddlyclip plug-in repository so that we can clear our doubts regarding the plug-in usage instead of creating new issues

**Comment by buggyj** [comment]
ok
