### ISSUE TITLE
Add variable type that would persist across 'rule actions'

### ISSUE THREAD

**Issue by buggyj** [buggyj/tiddlyclip-plugin#9]
When creating a number of tiddlers in the same clip action, in order to refer to a tiddler create in a previous part of the clip action, the name of that tiddler must be a made available to the refering tiddler.

At new type of variable can be constructed eg ":variableA"

**Comment by JulioCantarero** [comment]
Hi BJ,
Thank you for implementing the new variable type whose scope span across Rule Tiddlers.
I noticed that there seems to be a typo in the description above, as the new variable type uses the prefix '%' in your code, not ':'. So a variable of this type should be named "%vairableA" in the example above.
