### ISSUE TITLE
Tiddlyclip not showing the entire custom configurations in the context menu when used with multicolumn layout

### ISSUE THREAD

**Issue by arunnbabu81** [buggyj/tiddlyclip-plugin#97]
I was trying to use tiddlyclip with multicolumn plug in by BTC. When the multicolumn layout is active, the context menu shows only the default configuration that come with the plug in. User created custom tiddlyclip configurations appear in the context menu only when I change the layout back to default layout. Check in this demo.....https://multicolumn-krystal.tiddlyhost.com/

**Comment by buggyj** [comment]
the tiddler $:/plugins/bj/tiddlyclip/template needs to be transcluded some where... 

In the standard  layout there are a number of places where templates are include by tagging them. With non-standard layout this may not be case. If this is so there will be no way to get  tiddlyclip to work.

**Comment by arunnbabu81** [comment]
> the tiddler $:/plugins/bj/tiddlyclip/template needs to be transcluded some where...

Thanks for the suggestion. I was able to make it work by adding the `$:/plugins/bj/tiddlyclip/template` into the pagetemplate field of the ensemble created.

![image](https://user-images.githubusercontent.com/67494083/175829632-e0a13f6c-23d4-44fe-84c1-818660823199.png)


https://multicolumn-krystal.tiddlyhost.com/#%24%3A%2Fplugins%2FBTC%2Ftiddlywiki-multi-columns%2Fui%2FSideBarTabs%2FEnsemble
